//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Attendance.Model.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AttendanceEntities : DbContext
    {
        public AttendanceEntities()
            : base("name=AttendanceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ABSENCE_TYPE> ABSENCE_TYPE { get; set; }
        public virtual DbSet<ABSENT_LOG> ABSENT_LOG { get; set; }
        public virtual DbSet<ABSENT_TYPE> ABSENT_TYPE { get; set; }
        public virtual DbSet<ATTENDANCE> ATTENDANCE { get; set; }
        public virtual DbSet<COURSE> COURSE { get; set; }
        public virtual DbSet<DEPARTMENT> DEPARTMENT { get; set; }
        public virtual DbSet<EVENT> EVENT { get; set; }
        public virtual DbSet<EVENT_TYPE> EVENT_TYPE { get; set; }
        public virtual DbSet<GENDER> GENDER { get; set; }
        public virtual DbSet<HALL> HALL { get; set; }
        public virtual DbSet<LEVEL> LEVEL { get; set; }
        public virtual DbSet<LOCATION> LOCATION { get; set; }
        public virtual DbSet<PERSON> PERSON { get; set; }
        public virtual DbSet<PROGRAMME> PROGRAMME { get; set; }
        public virtual DbSet<ROLE> ROLE { get; set; }
        public virtual DbSet<SESSION> SESSION { get; set; }
        public virtual DbSet<STAFF> STAFF { get; set; }
        public virtual DbSet<STAFF_TYPE> STAFF_TYPE { get; set; }
        public virtual DbSet<STUDENT> STUDENT { get; set; }
        public virtual DbSet<STUDENT_LEVEL> STUDENT_LEVEL { get; set; }
        public virtual DbSet<USER> USER { get; set; }
        public virtual DbSet<MENU> MENU { get; set; }
        public virtual DbSet<MENU_GROUP> MENU_GROUP { get; set; }
        public virtual DbSet<MENU_IN_ROLE> MENU_IN_ROLE { get; set; }
    }
}
