//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Attendance.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class EVENT
    {
        public EVENT()
        {
            this.ATTENDANCE = new HashSet<ATTENDANCE>();
            this.ABSENT_LOG = new HashSet<ABSENT_LOG>();
        }
    
        public long Id { get; set; }
        public int Event_Type_Id { get; set; }
        public Nullable<long> Course_Id { get; set; }
        public Nullable<int> Hall_Id { get; set; }
        public System.DateTime Event_Start { get; set; }
        public System.DateTime Event_End { get; set; }
        public int Location_Id { get; set; }
        public System.DateTime Date { get; set; }
        public long User_Id { get; set; }
        public int Session_Id { get; set; }
        public int Programme_Id { get; set; }
        public int Department_Id { get; set; }
        public int Level_Id { get; set; }
    
        public virtual ICollection<ATTENDANCE> ATTENDANCE { get; set; }
        public virtual COURSE COURSE { get; set; }
        public virtual DEPARTMENT DEPARTMENT { get; set; }
        public virtual EVENT_TYPE EVENT_TYPE { get; set; }
        public virtual HALL HALL { get; set; }
        public virtual LEVEL LEVEL { get; set; }
        public virtual LOCATION LOCATION { get; set; }
        public virtual PROGRAMME PROGRAMME { get; set; }
        public virtual SESSION SESSION { get; set; }
        public virtual USER USER { get; set; }
        public virtual ICollection<ABSENT_LOG> ABSENT_LOG { get; set; }
    }
}
