//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Attendance.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class HALL
    {
        public HALL()
        {
            this.EVENT = new HashSet<EVENT>();
            this.STAFF = new HashSet<STAFF>();
            this.STUDENT = new HashSet<STUDENT>();
            this.STAFF_HALL = new HashSet<STAFF_HALL>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public bool Active { get; set; }
    
        public virtual ICollection<EVENT> EVENT { get; set; }
        public virtual ICollection<STAFF> STAFF { get; set; }
        public virtual ICollection<STUDENT> STUDENT { get; set; }
        public virtual ICollection<STAFF_HALL> STAFF_HALL { get; set; }
    }
}
