//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Attendance.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MENU
    {
        public MENU()
        {
            this.MENU_IN_ROLE = new HashSet<MENU_IN_ROLE>();
        }
    
        public long Menu_Id { get; set; }
        public string Controller { get; set; }
        public string Action { get; set; }
        public string Area { get; set; }
        public string Display_Name { get; set; }
        public bool Activated { get; set; }
        public int Menu_Group_Id { get; set; }
    
        public virtual ICollection<MENU_IN_ROLE> MENU_IN_ROLE { get; set; }
        public virtual MENU_GROUP MENU_GROUP { get; set; }
    }
}
