//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Attendance.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSON
    {
        public PERSON()
        {
            this.USER = new HashSet<USER>();
        }
    
        public long Id { get; set; }
        public string Last_Name { get; set; }
        public string First_Name { get; set; }
        public string Other_Name { get; set; }
        public string Phone_Number { get; set; }
        public string Email { get; set; }
        public string Passport_Url { get; set; }
        public int Gender_Id { get; set; }
    
        public virtual GENDER GENDER { get; set; }
        public virtual STAFF STAFF { get; set; }
        public virtual STUDENT STUDENT { get; set; }
        public virtual ICollection<USER> USER { get; set; }
    }
}
