//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Attendance.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class STAFF
    {
        public STAFF()
        {
            this.COURSE = new HashSet<COURSE>();
            this.STAFF_COURSE = new HashSet<STAFF_COURSE>();
            this.STAFF_HALL = new HashSet<STAFF_HALL>();
        }
    
        public long Person_Id { get; set; }
        public int Staff_Type_Id { get; set; }
        public string Registration_Number { get; set; }
        public Nullable<int> Department_Id { get; set; }
        public Nullable<int> Hall_Id { get; set; }
        public bool Active { get; set; }
        public bool Is_Lecturer { get; set; }
        public bool Is_Medical_Staff { get; set; }
        public bool Is_Student_Affairs { get; set; }
        public bool Is_Hall_Officer { get; set; }
    
        public virtual ICollection<COURSE> COURSE { get; set; }
        public virtual DEPARTMENT DEPARTMENT { get; set; }
        public virtual HALL HALL { get; set; }
        public virtual PERSON PERSON { get; set; }
        public virtual STAFF_TYPE STAFF_TYPE { get; set; }
        public virtual ICollection<STAFF_COURSE> STAFF_COURSE { get; set; }
        public virtual ICollection<STAFF_HALL> STAFF_HALL { get; set; }
    }
}
